--- 
Description: "Create an EC2 instance by AWS CloudFormation"
Resources: 
  EC2InstanceDemoSvr: 
    Properties: 
      AvailabilityZone: us-west-2a
      ImageId: ami-0d6621c01e8c2de2c
      InstanceType: t2.micro
      KeyName: keypairoregon
    Type: "AWS::EC2::Instance"
  SecurityGroupDemoSvrTraffic: 
    Properties: 
      GroupDescription: "Security Group for demo server"
      GroupName: SGcloudFomation
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          Description: "For traffic from Internet"
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      VpcId: vpc-e63e5d9e
    Type: "AWS::EC2::SecurityGroup"
